### ISSUE TITLE
포스팅 하단에 게시판 기능 추가

### ISSUE THREAD

**Issue by blissray** [TeamLab/jekyllDecent#8]
기존 팀랩 참고

**Comment by kimjeyoung** [comment]
![default](https://user-images.githubusercontent.com/20804734/38205199-a9687216-36e0-11e8-816f-68f417985131.PNG)

@blissray 교수님 이런걸 말씀하시는 건가요???

**Comment by kimjeyoung** [comment]
추가적으로 category가 너무 다방면이라 보여지는 메인페이지가 깔끔하지 않은 것 같아서 왼쪽 측면이나 상단부에 sidebar 하나 만들어서 category별로 포스팅 되도록 만드는 것이 나중에도 효율적일 것 같아서 같이 진행하겠습니다!

**Comment by blissray** [comment]
![image](https://user-images.githubusercontent.com/8847089/38206274-bb962114-36e4-11e8-81f6-9864d16315ae.png)
이거요.

**Comment by blissray** [comment]
포스팅에만 있으면 됩니다.
